# 01_process_dashboard.R
# Extracts, cleans, and pins California School Dashboard & Assistance data

library(tidyverse)
library(here)
library(pins)

options(scipen = 999)

# 1. Establish robust project paths and load helpers -------------------------
source(here("R", "data-urls.R"))
source(here("R", "load-files.R"))
source(here("R", "clean.R"))

# Connect to the local Pins board
local_board <- board_folder(here("data", "pins"))

# 3. Read Dashboard Indicator Files -------------------------------------------
message("Loading dashboard indicator files...")
dashboard_raw <- download_and_load_dashboard_set(dashboard_files) |>
  normalize_cde_names()

# Get the most recent name for *every* CDS code, even if they closed before max_year
current_names_codes <- dashboard_raw |>
  arrange(desc(reporting_year)) |>
  select(cds, county_name, district_name, school_name) |>
  distinct(cds, .keep_all = TRUE)

dashboard_raw <- dashboard_raw |>
  select(-county_name, -district_name, -school_name) |>
  left_join(current_names_codes, by = "cds")

# 4. Read & Normalize Assistance Files ----------------------------------------
message("Loading assistance files...")

# Use pmap to iterate over the assistance_files table from data-urls.R
raw_assistance_list <- pmap(
  assistance_files,
  function(name, url, sheet, start_row) {
    load_excel_from_cache(url, sheet = sheet, start_row = start_row)
  }
) |>
  set_names(assistance_files$name)

message("Normalizing assistance data...")
assistance <- normalize_assistance(raw_assistance_list)


# 5. Read & Normalize ESSA Files ----------------------------------------------
message("Loading ESSA files...")

# Use pmap to iterate over the essa_files table from data-urls.R
raw_essa_list <- pmap(essa_files, function(name, url, sheet, start_row) {
  # 1. Load the raw excel file
  df <- load_excel_from_cache(url, sheet = sheet, start_row = start_row)

  # 2. Force demographic columns to numeric (NAs will be introduced by coercion for "*")
  numeric_cols <- c(
    "aa",
    "ai",
    "as",
    "el",
    "fi",
    "fos",
    "hi",
    "hom",
    "pi",
    "sed",
    "swd",
    "tom",
    "wh",
    "enrollment_count"
  )

  existing_numeric_cols <- intersect(numeric_cols, names(df))

  df |>
    mutate(across(
      .cols = all_of(existing_numeric_cols),
      .fns = ~ as.numeric(na_if(.x, "*"))
    ))
}) |>
  set_names(essa_files$name)

essa <- normalize_essa(raw_essa_list)

# 6. Join Assistance & Compute Eligibility ------------------------------------
message("Merging dashboard with assistance and computing eligibility...")

dashboard_clean <- dashboard_raw |>
  mutate(
    student_group = if_else(
      is.na(student_group) & indicator == "ELPI",
      "EL",
      student_group
    ),
    student_group_long = recode_values(
      student_group,
      "ALL" ~ "All students",
      "AA" ~ "Black/African American",
      "AI" ~ "American Indian or Alaska Native",
      "AS" ~ "Asian",
      "FI" ~ "Filipino",
      "HI" ~ "Hispanic",
      "PI" ~ "Pacific Islander",
      "WH" ~ "White",
      "MR" ~ "Multiple Races/Two or more",
      "EL" ~ "English Learner",
      "ELO" ~ "English Learners Only",
      "RFP" ~ "RFEPs Only",
      "EO" ~ "English Only",
      "SBA" ~ "Smarter Balanced Assessment",
      "CAA" ~ "CA Alternative Assessment",
      "SED" ~ "Socioeconomically Disadvantaged",
      "SWD" ~ "Students with Disabilities",
      "FOS" ~ "Foster Youth",
      "HOM" ~ "Homeless Youth",
      "TOM" ~ "Multiple Races/Two or more",
      "LTEL" ~ "Long-Term English Learner",
      default = student_group
    ),
    county_name = recode_values(
      rtype,
      "X" ~ "CA State Aggregate",
      default = county_name
    ),
    school_name = case_when(
      rtype == "D" & is.na(school_name) ~ "District Aggregate",
      TRUE ~ school_name
    )
  )

check_priorities <- function(priority, priorities) {
  priority %in% unlist(priorities)
}

dashboard_with_assistance <- dashboard_clean |>
  left_join(
    # Drop the redundant columns generated by normalize_cde_names before joining
    assistance |>
      select(-c(academic_year, county_code, district_code, school_code)),
    by = join_by(cds, student_group, reporting_year, charter_flag)
  ) |>
  left_join(
    priority_eligibility_lookup,
    by = join_by(assistance_current == assistance)
  ) |>
  rename(priorities_current = priorities) |>
  left_join(
    priority_eligibility_lookup,
    by = join_by(assistance_prior == assistance)
  ) |>
  rename(priorities_prior = priorities) |>
  left_join(priority_eligibility_lookup, by = "assistance")

dashboard_with_elibibility <- dashboard_with_assistance |>
  mutate(
    priority_eligible = if_else(
      is.na(charter_flag),
      map2_lgl(priority, priorities, check_priorities),
      assistance_status == "Differentiated Assistance" &
        map2_lgl(priority, priorities_current, check_priorities)
    )
  ) |>
  select(-starts_with("priorities"))

message("Computing indicator eligibility and priority-4 summary...")
priority_4_tbl <- compute_priority4_summary(dashboard_with_elibibility)

ca_dashboard <- dashboard_with_elibibility |>
  left_join(
    priority_4_tbl,
    by = join_by(cds, reporting_year, student_group_long)
  ) |>
  mutate(
    indicator_eligible = case_when(
      priority == 8 & priority_eligible ~ TRUE,
      priority != 4 & priority_eligible & color == "1" ~ TRUE,
      priority != 4 &
        priority_eligible &
        reporting_year == 2022 &
        statuslevel == 1 ~ TRUE,
      student_group != "LTEL" &
        priority == 4 &
        indicator == "ELA" &
        caaspp_eligible == TRUE ~ TRUE,
      student_group != "LTEL" &
        priority == 4 &
        indicator == "Math" &
        caaspp_eligible == TRUE ~ TRUE,
      priority == 4 & indicator == "ELPI" & elpi_eligible == TRUE ~ TRUE,
      TRUE ~ FALSE
    )
  ) |>
  # UPDATE THIS LINE: Use any_of() to cleanly drop all pivoted Priority 4 columns
  select(-any_of(c("ELA", "Math", "ELPI", "science", "growth", "caaspp_eligible", "elpi_eligible")))

small_dashboard <- ca_dashboard |>
  filter(county_name %in% c("Solano", "CA State Aggregate"))

# 7. Download & Clean Teacher Data --------------------------------------------
message("Loading teacher credentialing data...")
teacher_assignments <- load_txt_from_cache(teacher_assignments_url)
teacher_assignments_clean <- normalize_teacher_assignments(teacher_assignments)
solano_teachers <- teacher_assignments_clean |> filter(county_name == "Solano")

# 8. Join with ESSA for local dashboard_essa ----------------------------------
dashboard_essa <- ca_dashboard |>
  filter(county_name == "Solano") |>
  left_join(
    essa,
    # Drop the names from the join keys to prevent duplicate rows
    # if a school changed its name between years in the ESSA file
    by = join_by(
      cds,
      student_group,
      reporting_year
    ),
    suffix = c("", "_essa") # In case ESSA brings its own name columns, don't break ours
  )

# 8.5 Free up memory before pinning -------------------------------------------
message("Cleaning up intermediate objects to free RAM...")

# Remove massive intermediate dataframes that we no longer need
rm(
  dashboard_raw,
  dashboard_clean,
  dashboard_with_assistance,
  dashboard_with_elibibility,
  raw_assistance_list,
  raw_essa_list,
  assistance,
  essa
)

# Force R to release the memory back to your operating system immediately
gc()

# 9. Pin to Local Board -------------------------------------------------------
message("Pinning all datasets to the local board...")

pin_write(
  local_board,
  ca_dashboard,
  name = "ca_dashboard_full",
  type = "parquet",
  title = "Full CA Dashboard"
)
pin_write(
  local_board,
  small_dashboard,
  name = "solano_dashboard",
  type = "parquet",
  title = "Solano Dashboard"
)

pin_write(
  local_board,
  dashboard_essa,
  name = "solano_dashboard_essa",
  type = "parquet",
  title = "Solano Dashboard + ESSA Joined"
)
pin_write(
  local_board,
  teacher_assignments_clean,
  name = "ca_teacher_assignments",
  type = "parquet",
  title = "CA Teacher Assignments"
)
pin_write(
  local_board,
  solano_teachers,
  name = "solano_teacher_assignments",
  type = "parquet",
  title = "Solano Teacher Assignments"
)

# Load the raw growth file
growth_raw <- load_txt_from_cache(growth_url) |>
  normalize_cde_names() |> 
  rename(performance_category = performancecategory)

# Keep it lean! Only select what you actually need
solano_growth <- growth_raw |>
  filter(county_name == "Solano") |>
  mutate(
    student_group_long = recode_values(
      student_group,
      "ALL" ~ "All students",
      "AA" ~ "Black/African American",
      "AI" ~ "American Indian or Alaska Native",
      "AS" ~ "Asian",
      "FI" ~ "Filipino",
      "HI" ~ "Hispanic",
      "PI" ~ "Pacific Islander",
      "WH" ~ "White",
      "MR" ~ "Multiple Races/Two or more",
      "EL" ~ "English Learner",
      "ELO" ~ "English Learners Only",
      "RFP" ~ "RFEPs Only",
      "EO" ~ "English Only",
      "SBA" ~ "Smarter Balanced Assessment",
      "CAA" ~ "CA Alternative Assessment",
      "SED" ~ "Socioeconomically Disadvantaged",
      "SWD" ~ "Students with Disabilities",
      "FOS" ~ "Foster Youth",
      "HOM" ~ "Homeless Youth",
      "TOM" ~ "Multiple Races/Two or more",
      "LTEL" ~ "Long-Term English Learner",
      default = student_group
    ),
    # Map the performance categories using the exact layout from CDE
    # Wrapping in as.character() just in case vroom guessed the column as numeric
    performance_category_text = recode_values(
      as.character(performance_category),
      "1" ~ "Minimal Growth",
      "2" ~ "Moderate Growth",
      "3" ~ "Average Growth",
      "4" ~ "Accelerated Growth",
      "5" ~ "Exceptional Growth",
      "0" ~ "No Performance Category",
      default = NA_character_
    )
  )

# Pin it!
pin_write(
  local_board,
  solano_growth,
  name = "solano_academic_growth",
  type = "parquet",
  title = "Solano Academic Growth"
)

message("Success! All dashboard data refreshed and pinned.")
